### ISSUE TITLE
not syncdb but migrate

### ISSUE THREAD

**Issue by tijs** [dstufft/django-postmark#1]
small doc error: you say to run syncdb but it seems you use south instead. also pytz is a requirement not yet in your setup.py perhaps?

**Comment by dstufft** [comment]
You are right, That'll teach me for writing the setup.py and README.rst when i'm tired.

**Comment by tijs** [comment]
Well the trick is to write -something- first right. You can deal with the typos later ;)

**Comment by camilonova** [comment]
You can close this issue

**Comment by dstufft** [comment]
Updated the Docs to reflect the fact that if South is installed then the correct command is migrate.
